fix: removing comments
Signed-off-by: Scott Schreckengaust <scottschreckengaust@users.noreply.github.com>

diff --git a/.github/workflows/code-review-process.yml b/.github/workflows/code-review-process.yml
--- a/.github/workflows/code-review-process.yml
+++ b/.github/workflows/code-review-process.yml
@@ -10,7 +10,7 @@ jobs:
     name: Automated Code Review Acknowledgement
     runs-on: ubuntu-latest
     permissions:
-      checks: write   # Permission to create a Check Run
+      checks: write
     steps:
       ####################################################
       # Update the status to show that the queued message
@@ -20,7 +20,6 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
-          echo "${{ env.IS_THERE_AN_AWS_ROLE_ARN_TO_ASSUME }}"
           gh api -X PATCH -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -f 'status=in_progress' \
@@ -32,19 +31,16 @@ jobs:
     name: Automated Code Review Processing
     runs-on: ubuntu-latest
     permissions:
-      checks: write   # Permission to create a Check Run
+      checks: write
     needs: [code-review-acknowledgement]
     outputs:
       result: ${{ steps.report.outputs.result }}
-    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#env-context
-    # `if` cannot access env at the job level
     steps:
-      ####################################################
-      # Actually, we'll just sleep to simulate some work
-      ####################################################
       - name: Setup AWS credentials
         id: setup-aws-credentials
         uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
+        # secrets.AWS_ROLE_ARN_TO_ASSUME cannot used in `if` when undefined.
+        # env.IS_THERE_AN_AWS_ROLE_ARN_TO_ASSUME not available at the `if` for job
         if: ${{ env.IS_THERE_AN_AWS_ROLE_ARN_TO_ASSUME == 'true' && vars.AWS_REGION }}
         with:
           role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
@@ -52,23 +48,22 @@ jobs:
           role-duration-seconds: 7200
           mask-aws-account-id: true
 
-      #####################################################
-      # Replace with long-running process
-      #####################################################
       - name: Processing
         id: processor
         if: success()
-        timeout-minutes: 120  # match the credentials token
+        timeout-minutes: 1 # 120  ## match the credentials token
         run: |
-          sleep 10
-          # Uncomment to test failure
-          # exit 99
+          ####################################################
+          # Sleep to simulate some work
+          ####################################################
+          sleep 5    #  
+          # sleep 60 # simulate timeout
+          # exit 99  # simulate a process failure
+          exit 0
 
       - name: Report Result
         id: report
         if: always()
-        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#cancelled
-        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#operators
         run: |
           echo "steps.processor.conclusion: ${{ steps.processor.conclusion }}"
           echo "result=${{ steps.processor.conclusion }}" >> $GITHUB_OUTPUT
